export const GameEvent = {
    NEW_GAME: "NEW_GAME",
    LEVEL_COMPLETED: "LEVEL_COMPLETE",
    SELECT_FOOD: "SELECT_FOOD",
    ON_GOAL_COMPLETED: "ON_GOAL_COMPLETED",
    LEVEL_LOSE: "LEVEL_LOSE"
    // ON_NEW_TARGET_SPAWN: "ON_NEW_TARGET_SPAWN"
}