export const GameEvent = {
    NEW_GAME: "NEW_GAME",
    LEVEL_COMPLETED: "LEVEL_COMPLETED",
    LEVEL_FAILED: "LEVEL_FAILED",
    ON_MATCHED: "ON_MATCHED",
    ON_NEW_TARGET_SPAWN: "ON_NEW_TARGET_SPAWN",
    BUFFER_FULL: "BUFFER_FULL",
    FOOD_CONSUMED: "FOOD_CONSUMED"
}